/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Login_Signup_Controller;
import DAO.UserDAO;
import model.User;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class LOGIN_UI extends FORM {

    /**
     * Creates new form LOGIN_UI
     */
    public LOGIN_UI() {

        initComponents();
        Button_sign_in.setLabel("Sign in");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        create_account = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Button_sign_in = new View_Custom_pannel.RoundRect_Blue_Button();
        txt_error_pass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1117, 680));
        setPreferredSize(new java.awt.Dimension(1117, 680));
        setResizable(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhminhhoalon_rs.jpg"))); // NOI18N
        getContentPane().add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Password");

        jLabel1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 65, 187));
        jLabel1.setText("Login here");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 37, 37));
        jLabel2.setText("Welcome back you've  been missed!");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Username");

        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        create_account.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        create_account.setForeground(new java.awt.Color(73, 73, 73));
        create_account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_account.setText("Create new account");
        create_account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create_account.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        create_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_accountMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture3.png"))); // NOI18N

        Button_sign_in.setBackground(new java.awt.Color(31, 65, 187));
        Button_sign_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_sign_inMouseClicked(evt);
            }
        });

        txt_error_pass.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_error_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(create_account, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_error_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(create_account, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_accountMouseClicked
        // TODO add your handling code here:
        Login_Signup_Controller.Switch_UI(LOGIN_UI.this, new REGISTER_UI());
       
    }//GEN-LAST:event_create_accountMouseClicked

    private void Button_sign_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_sign_inMouseClicked
        // TODO add your handling code here:
        List<User> lstUser = new ArrayList<>();
        try{
            lstUser = UserDAO.getInstance().getAll();
        } catch (Exception e) {
            e.printStackTrace();
        }
        String username = txt_username.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        boolean isAuthenticated = false;

        for( User user : lstUser){
            if(user.getName().equals(username) && user.getPassword().equals(password)){
                        isAuthenticated = true;
                        Login_Signup_Controller.Switch_UI(LOGIN_UI.this, new MAIN_UI());
                        break;
            }
        }
        if (!isAuthenticated) {
            txt_username.setBorder(new LineBorder(Color.RED, 1));
            jPasswordField1.setBorder(new LineBorder(Color.RED, 1));
            txt_error_pass.setText("Username or password incorrectly!");
            shake(jPasswordField1);
            shake(txt_username);
            txt_username.requestFocus(); // Đảm bảo focus nằm trong trường văn bản
            txt_username.repaint(); // Làm mới giao diện của thành phần
            jPasswordField1.setText("");
            txt_username.setText("");
        }
    }//GEN-LAST:event_Button_sign_inMouseClicked


    private static final int SHAKE_DURATION = 500; // Thời gian rung (ms)
    private static final int SHAKE_DISTANCE = 2; // Khoảng cách rung (pixel)
    private void shake(JComponent component) {
        int posx = component.getX();
        Timer timer = new Timer(50, null);
        timer.addActionListener(new ActionListener() {
            int shakes = 0;
            int direction = 1; // 1 = phải, -1 = trái

            @Override
            public void actionPerformed(ActionEvent e) {

                if (shakes < SHAKE_DURATION / 50) { // Chạy trong thời gian chỉ định
                    int x = component.getX() + (direction * SHAKE_DISTANCE);
                    component.setLocation(x, component.getY());
                    direction *= -1; // Đổi hướng
                    shakes++;
                } else {
                    timer.stop(); // Dừng timer
                    component.setLocation(posx, component.getY()); // Trở về vị trí ban đầu (có thể thay đổi vị trí này)
                    txt_username.setBorder(new LineBorder(Color.BLACK, 1));
                    jPasswordField1.setBorder(new LineBorder(Color.BLACK, 1));
                }
            }
        });

        timer.start(); // Bắt đầu rung
    }


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View_Custom_pannel.RoundRect_Blue_Button Button_sign_in;
    private javax.swing.JLabel create_account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel txt_error_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
