/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.UserDAO;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Admin
 */
public class MAIN_UI extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_UI
     */
    public MAIN_UI() {

        initComponents();
        this.setDefalutComponent();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoot = new javax.swing.JPanel();
        TaskBarPanel = new javax.swing.JPanel();
        Order_Taskbar = new View_Custom_pannel.Round_Rect_Button_Logo();
        Leaderboard_Taskbar = new View_Custom_pannel.Round_Rect_Button_Logo();
        LogoPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(2560, 1600));

        panelRoot.setLayout(new java.awt.BorderLayout());

        TaskBarPanel.setBackground(new java.awt.Color(39, 49, 66));
        TaskBarPanel.setPreferredSize(new java.awt.Dimension(240, 0));

        Order_Taskbar.setBackground(new java.awt.Color(39, 49, 66));
        TaskBarPanel.add(Order_Taskbar);

        Leaderboard_Taskbar.setBackground(new java.awt.Color(39, 49, 66));
        TaskBarPanel.add(Leaderboard_Taskbar);

        panelRoot.add(TaskBarPanel, java.awt.BorderLayout.WEST);

        LogoPanel.setBackground(new java.awt.Color(39, 49, 66));
        LogoPanel.setPreferredSize(new java.awt.Dimension(2560, 70));

        Logo.setBackground(new java.awt.Color(39, 49, 66));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 128, 255));
        jLabel1.setText("DBCD");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tour");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark32x32.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1988, Short.MAX_VALUE))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRoot.add(LogoPanel, java.awt.BorderLayout.PAGE_START);

        CenterPanel.setBackground(new java.awt.Color(27, 36, 49));

        javax.swing.GroupLayout CenterPanelLayout = new javax.swing.GroupLayout(CenterPanel);
        CenterPanel.setLayout(CenterPanelLayout);
        CenterPanelLayout.setHorizontalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CenterPanelLayout.setVerticalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRoot.add(CenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

        if(i==0){
            dash(jLabel4);
            jLabel3.setForeground(Color.decode("#202224"));
            TaskBarPanel.setBackground(Color.decode("#FFFFFF"));
            Logo.setBackground(Color.decode("#FFFFFF"));
            CenterPanel.setBackground(Color.decode("#F5F6FA"));
            LogoPanel.setBackground(Color.decode("#FFFFFF"));
            Order_Taskbar.getjLabel1().setForeground(Color.decode("#202224"));
            Order_Taskbar.setBackground(Color.decode("#FFFFFF"));
            Order_Taskbar.setLogo(new javax.swing.ImageIcon(getClass().getResource("/orderblack.png")));
            Leaderboard_Taskbar.getjLabel1().setForeground(Color.decode("#202224"));
            Leaderboard_Taskbar.setBackground(Color.decode("#FFFFFF"));
            Leaderboard_Taskbar.setLogo(new javax.swing.ImageIcon(getClass().getResource("/heartblack32.png")));
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightblack.png")));
            Order_Taskbar.setColorDefault("#FFFFFF");
            Leaderboard_Taskbar.setColorDefault("#FFFFFF");
            i = 1;
        }
        else{
            dash(jLabel4);
            jLabel3.setForeground(Color.decode("#FFFFF"));
            TaskBarPanel.setBackground(Color.decode("#273142"));
            Logo.setBackground(Color.decode("#273142"));
            CenterPanel.setBackground(Color.decode("#1B2431"));
            LogoPanel.setBackground(Color.decode("#273142"));
            Order_Taskbar.getjLabel1().setForeground(Color.decode("#FFFFFF"));
            Order_Taskbar.setBackground(Color.decode("#273142"));
            Order_Taskbar.setLogo(new javax.swing.ImageIcon(getClass().getResource("/shop32x32.png")));
            Leaderboard_Taskbar.getjLabel1().setForeground(Color.decode("#FFFFFF"));
            Leaderboard_Taskbar.setBackground(Color.decode("#273142"));
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark32x32.png")));
            Leaderboard_Taskbar.setLogo(new javax.swing.ImageIcon(getClass().getResource("/heartwhite32.png")));
            Order_Taskbar.setColorDefault("#273142");
            Leaderboard_Taskbar.setColorDefault("#273142");
            i=0;
        }
    }//GEN-LAST:event_jLabel4MouseClicked
    /**
     * @param args the command line arguments
     */
    int i = 0;
    private void setDefalutComponent(){
        Order_Taskbar.setColorDefault("#273142");
        Order_Taskbar.setColorHover("#4880FF");
        Order_Taskbar.setLabel("Order Tour");
        Order_Taskbar.setLogo(new javax.swing.ImageIcon(getClass().getResource("/shop32x32.png")));
        Leaderboard_Taskbar.setColorDefault("#273142");
        Leaderboard_Taskbar.setColorHover("#4880FF");
        Leaderboard_Taskbar.setLabel("Favourite");
        Leaderboard_Taskbar.setLogo(new javax.swing.ImageIcon(getClass().getResource("/heartwhite32.png")));
        repaint();
    }
    private int DASH_DURATION = 8;
    private int direction = 1;
    private void dash(JComponent component) {
        //int posx = component.getX();
        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            int shakes = 0;
            @Override
            public void actionPerformed(ActionEvent e) {
                if (shakes < DASH_DURATION) { // Chạy trong thời gian chỉ định
                    int x = component.getX() + (direction * DASH_DURATION);
                    component.setLocation(x, component.getY());
//                    direction *= -1; // Đổi hướng
                    shakes++;
                } else {
                    timer.stop(); // Dừng timer
                    direction *= -1;
                   // component.setLocation(posx, component.getY()); // Trở về vị trí ban đầu (có thể thay đổi vị trí này)
                }
            }
        });

        timer.start(); // Bắt đầu rung
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private View_Custom_pannel.Round_Rect_Button_Logo Leaderboard_Taskbar;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel LogoPanel;
    private View_Custom_pannel.Round_Rect_Button_Logo Order_Taskbar;
    private javax.swing.JPanel TaskBarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelRoot;
    // End of variables declaration//GEN-END:variables
}
